kind: Service
apiVersion: v1
metadata:
  labels:
{{ include "mongodb.labels.stakater" . | indent 4 }}
{{ include "mongodb.labels.chart" . | indent 4 }}
  name: {{ template "mongodb.name" . }}
spec:
  selector:
{{ toYaml .Values.mongodb.deployment.podLabels | indent 4 }}
  ports:
  - name: web
    port: {{ .Values.mongodb.deployment.container.port }}
    protocol: TCP
    targetPort: {{ .Values.mongodb.deployment.container.port }}